"""empty message

Revision ID: 0e7cae927b5b
Revises: 672833020b45
Create Date: 2019-08-24 15:56:50.744545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7cae927b5b'
down_revision = '672833020b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_analisis',
    sa.Column('cod_tipo_analisis', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_analisis', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_analisis'),
    sa.UniqueConstraint('nombre_tipo_analisis')
    )
    op.create_index(op.f('ix_tipo_analisis_cod_tipo_analisis'), 'tipo_analisis', ['cod_tipo_analisis'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_analisis_cod_tipo_analisis'), table_name='tipo_analisis')
    op.drop_table('tipo_analisis')
    # ### end Alembic commands ###
