"""empty message

Revision ID: 1492da312f6d
Revises: af8db760e0a5
Create Date: 2019-08-23 23:11:45.150934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1492da312f6d'
down_revision = 'af8db760e0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estado_planificacion', sa.Column('nombre_estado', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'estado_planificacion', ['nombre_estado'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estado_planificacion', type_='unique')
    op.drop_column('estado_planificacion', 'nombre_estado')
    # ### end Alembic commands ###
