"""empty message

Revision ID: 507db19302b9
Revises: 
Create Date: 2019-08-29 00:31:11.857773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507db19302b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('cod_actividad', sa.Integer(), nullable=False),
    sa.Column('nombre_actividad', sa.String(length=32), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_actividad'),
    sa.UniqueConstraint('nombre_actividad')
    )
    op.create_index(op.f('ix_actividad_cod_actividad'), 'actividad', ['cod_actividad'], unique=False)
    op.create_table('estado_planificacion',
    sa.Column('cod_estado_planificacion', sa.Integer(), nullable=False),
    sa.Column('nombre_estado_planificacion', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_estado_planificacion'),
    sa.UniqueConstraint('nombre_estado_planificacion')
    )
    op.create_index(op.f('ix_estado_planificacion_cod_estado_planificacion'), 'estado_planificacion', ['cod_estado_planificacion'], unique=False)
    op.create_table('opcion',
    sa.Column('cod_opcion', sa.Integer(), nullable=False),
    sa.Column('nombre_opcion', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cod_opcion'),
    sa.UniqueConstraint('nombre_opcion')
    )
    op.create_index(op.f('ix_opcion_cod_opcion'), 'opcion', ['cod_opcion'], unique=False)
    op.create_table('permiso',
    sa.Column('cod_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre_permiso', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_permiso'),
    sa.UniqueConstraint('nombre_permiso')
    )
    op.create_index(op.f('ix_permiso_cod_permiso'), 'permiso', ['cod_permiso'], unique=False)
    op.create_table('recomendacion',
    sa.Column('cod_recomendacion', sa.Integer(), nullable=False),
    sa.Column('nombre_recomendacion', sa.String(length=32), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_recomendacion'),
    sa.UniqueConstraint('nombre_recomendacion')
    )
    op.create_index(op.f('ix_recomendacion_cod_recomendacion'), 'recomendacion', ['cod_recomendacion'], unique=False)
    op.create_table('tipo_analisis',
    sa.Column('cod_tipo_analisis', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_analisis', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_analisis'),
    sa.UniqueConstraint('nombre_tipo_analisis')
    )
    op.create_index(op.f('ix_tipo_analisis_cod_tipo_analisis'), 'tipo_analisis', ['cod_tipo_analisis'], unique=False)
    op.create_table('tipo_dato',
    sa.Column('cod_tipo_dato', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_dato', sa.String(length=32), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_dato'),
    sa.UniqueConstraint('nombre_tipo_dato')
    )
    op.create_index(op.f('ix_tipo_dato_cod_tipo_dato'), 'tipo_dato', ['cod_tipo_dato'], unique=False)
    op.create_table('tipo_parametro',
    sa.Column('cod_tipo_parametro', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_parametro', sa.String(length=32), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_parametro'),
    sa.UniqueConstraint('nombre_tipo_parametro')
    )
    op.create_index(op.f('ix_tipo_parametro_cod_tipo_parametro'), 'tipo_parametro', ['cod_tipo_parametro'], unique=False)
    op.create_table('tipo_plan',
    sa.Column('cod_tipo_plan', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_plan', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_plan'),
    sa.UniqueConstraint('nombre_tipo_plan')
    )
    op.create_index(op.f('ix_tipo_plan_cod_tipo_plan'), 'tipo_plan', ['cod_tipo_plan'], unique=False)
    op.create_table('tipo_planificacion',
    sa.Column('cod_tipo_planificacion', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_planificacion', sa.String(length=32), nullable=False),
    sa.Column('desc_tipo_planificacion', sa.Text(), nullable=True),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_planificacion'),
    sa.UniqueConstraint('nombre_tipo_planificacion')
    )
    op.create_index(op.f('ix_tipo_planificacion_cod_tipo_planificacion'), 'tipo_planificacion', ['cod_tipo_planificacion'], unique=False)
    op.create_table('parametro',
    sa.Column('cod_parametro', sa.Integer(), nullable=False),
    sa.Column('nombre_parametro', sa.String(length=32), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.Column('fk_cod_tipo_parametro', sa.Integer(), nullable=True),
    sa.Column('fk_cod_tipo_dato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cod_tipo_dato'], ['tipo_dato.cod_tipo_dato'], ),
    sa.ForeignKeyConstraint(['fk_cod_tipo_parametro'], ['tipo_parametro.cod_tipo_parametro'], ),
    sa.PrimaryKeyConstraint('cod_parametro'),
    sa.UniqueConstraint('nombre_parametro')
    )
    op.create_index(op.f('ix_parametro_cod_parametro'), 'parametro', ['cod_parametro'], unique=False)
    op.create_index(op.f('ix_parametro_fk_cod_tipo_dato'), 'parametro', ['fk_cod_tipo_dato'], unique=False)
    op.create_index(op.f('ix_parametro_fk_cod_tipo_parametro'), 'parametro', ['fk_cod_tipo_parametro'], unique=False)
    op.create_table('actividad_parametro',
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.Column('fk_cod_parametro', sa.Integer(), nullable=False),
    sa.Column('fk_cod_actividad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_cod_actividad'], ['actividad.cod_actividad'], ),
    sa.ForeignKeyConstraint(['fk_cod_parametro'], ['parametro.cod_parametro'], ),
    sa.PrimaryKeyConstraint('fk_cod_parametro', 'fk_cod_actividad')
    )
    op.create_index(op.f('ix_actividad_parametro_fk_cod_actividad'), 'actividad_parametro', ['fk_cod_actividad'], unique=False)
    op.create_index(op.f('ix_actividad_parametro_fk_cod_parametro'), 'actividad_parametro', ['fk_cod_parametro'], unique=False)
    op.create_table('parametro_opcion',
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.Column('fk_cod_parametro', sa.Integer(), nullable=False),
    sa.Column('fk_cod_opcion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_cod_opcion'], ['opcion.cod_opcion'], ),
    sa.ForeignKeyConstraint(['fk_cod_parametro'], ['parametro.cod_parametro'], ),
    sa.PrimaryKeyConstraint('fk_cod_parametro', 'fk_cod_opcion')
    )
    op.create_index(op.f('ix_parametro_opcion_fk_cod_opcion'), 'parametro_opcion', ['fk_cod_opcion'], unique=False)
    op.create_index(op.f('ix_parametro_opcion_fk_cod_parametro'), 'parametro_opcion', ['fk_cod_parametro'], unique=False)
    op.create_table('recomendacion_parametro',
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.Column('fk_cod_parametro', sa.Integer(), nullable=False),
    sa.Column('fk_cod_recomendacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_cod_parametro'], ['parametro.cod_parametro'], ),
    sa.ForeignKeyConstraint(['fk_cod_recomendacion'], ['recomendacion.cod_recomendacion'], ),
    sa.PrimaryKeyConstraint('fk_cod_parametro', 'fk_cod_recomendacion')
    )
    op.create_index(op.f('ix_recomendacion_parametro_fk_cod_parametro'), 'recomendacion_parametro', ['fk_cod_parametro'], unique=False)
    op.create_index(op.f('ix_recomendacion_parametro_fk_cod_recomendacion'), 'recomendacion_parametro', ['fk_cod_recomendacion'], unique=False)
    op.create_table('tipo_analisis_param',
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.Column('fk_cod_parametro', sa.Integer(), nullable=False),
    sa.Column('fk_cod_tipo_analisis', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_cod_parametro'], ['parametro.cod_parametro'], ),
    sa.ForeignKeyConstraint(['fk_cod_tipo_analisis'], ['tipo_analisis.cod_tipo_analisis'], ),
    sa.PrimaryKeyConstraint('fk_cod_parametro', 'fk_cod_tipo_analisis')
    )
    op.create_index(op.f('ix_tipo_analisis_param_fk_cod_parametro'), 'tipo_analisis_param', ['fk_cod_parametro'], unique=False)
    op.create_index(op.f('ix_tipo_analisis_param_fk_cod_tipo_analisis'), 'tipo_analisis_param', ['fk_cod_tipo_analisis'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_analisis_param_fk_cod_tipo_analisis'), table_name='tipo_analisis_param')
    op.drop_index(op.f('ix_tipo_analisis_param_fk_cod_parametro'), table_name='tipo_analisis_param')
    op.drop_table('tipo_analisis_param')
    op.drop_index(op.f('ix_recomendacion_parametro_fk_cod_recomendacion'), table_name='recomendacion_parametro')
    op.drop_index(op.f('ix_recomendacion_parametro_fk_cod_parametro'), table_name='recomendacion_parametro')
    op.drop_table('recomendacion_parametro')
    op.drop_index(op.f('ix_parametro_opcion_fk_cod_parametro'), table_name='parametro_opcion')
    op.drop_index(op.f('ix_parametro_opcion_fk_cod_opcion'), table_name='parametro_opcion')
    op.drop_table('parametro_opcion')
    op.drop_index(op.f('ix_actividad_parametro_fk_cod_parametro'), table_name='actividad_parametro')
    op.drop_index(op.f('ix_actividad_parametro_fk_cod_actividad'), table_name='actividad_parametro')
    op.drop_table('actividad_parametro')
    op.drop_index(op.f('ix_parametro_fk_cod_tipo_parametro'), table_name='parametro')
    op.drop_index(op.f('ix_parametro_fk_cod_tipo_dato'), table_name='parametro')
    op.drop_index(op.f('ix_parametro_cod_parametro'), table_name='parametro')
    op.drop_table('parametro')
    op.drop_index(op.f('ix_tipo_planificacion_cod_tipo_planificacion'), table_name='tipo_planificacion')
    op.drop_table('tipo_planificacion')
    op.drop_index(op.f('ix_tipo_plan_cod_tipo_plan'), table_name='tipo_plan')
    op.drop_table('tipo_plan')
    op.drop_index(op.f('ix_tipo_parametro_cod_tipo_parametro'), table_name='tipo_parametro')
    op.drop_table('tipo_parametro')
    op.drop_index(op.f('ix_tipo_dato_cod_tipo_dato'), table_name='tipo_dato')
    op.drop_table('tipo_dato')
    op.drop_index(op.f('ix_tipo_analisis_cod_tipo_analisis'), table_name='tipo_analisis')
    op.drop_table('tipo_analisis')
    op.drop_index(op.f('ix_recomendacion_cod_recomendacion'), table_name='recomendacion')
    op.drop_table('recomendacion')
    op.drop_index(op.f('ix_permiso_cod_permiso'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_opcion_cod_opcion'), table_name='opcion')
    op.drop_table('opcion')
    op.drop_index(op.f('ix_estado_planificacion_cod_estado_planificacion'), table_name='estado_planificacion')
    op.drop_table('estado_planificacion')
    op.drop_index(op.f('ix_actividad_cod_actividad'), table_name='actividad')
    op.drop_table('actividad')
    # ### end Alembic commands ###
