"""empty message

Revision ID: 672833020b45
Revises: 739b4cc016df
Create Date: 2019-08-24 15:53:23.676540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672833020b45'
down_revision = '739b4cc016df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_planificacion',
    sa.Column('cod_tipo_planificacion', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_planificacion', sa.String(length=32), nullable=False),
    sa.Column('desc_tipo_planificacion', sa.Text(), nullable=True),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_planificacion'),
    sa.UniqueConstraint('nombre_tipo_planificacion')
    )
    op.create_index(op.f('ix_tipo_planificacion_cod_tipo_planificacion'), 'tipo_planificacion', ['cod_tipo_planificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_planificacion_cod_tipo_planificacion'), table_name='tipo_planificacion')
    op.drop_table('tipo_planificacion')
    # ### end Alembic commands ###
