"""empty message

Revision ID: 739b4cc016df
Revises: 
Create Date: 2019-08-23 23:31:44.279722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739b4cc016df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_planificacion',
    sa.Column('cod_estado_planificacion', sa.Integer(), nullable=False),
    sa.Column('nombre_estado_planificacion', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_estado_planificacion'),
    sa.UniqueConstraint('nombre_estado_planificacion')
    )
    op.create_index(op.f('ix_estado_planificacion_cod_estado_planificacion'), 'estado_planificacion', ['cod_estado_planificacion'], unique=False)
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_id'), 'hotel', ['id'], unique=False)
    op.create_table('opcion',
    sa.Column('cod_opcion', sa.Integer(), nullable=False),
    sa.Column('nombre_opcion', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cod_opcion'),
    sa.UniqueConstraint('nombre_opcion')
    )
    op.create_index(op.f('ix_opcion_cod_opcion'), 'opcion', ['cod_opcion'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opcion_cod_opcion'), table_name='opcion')
    op.drop_table('opcion')
    op.drop_index(op.f('ix_hotel_id'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_estado_planificacion_cod_estado_planificacion'), table_name='estado_planificacion')
    op.drop_table('estado_planificacion')
    # ### end Alembic commands ###
