"""empty message

Revision ID: af8db760e0a5
Revises: fb4c1b933b7f
Create Date: 2019-08-23 21:45:31.980043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8db760e0a5'
down_revision = 'fb4c1b933b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_planificacion',
    sa.Column('cod_estado_planificacion', sa.Integer(), nullable=False),
    sa.Column('nombre_estado_planificacion', sa.String(length=60), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cod_estado_planificacion'),
    sa.UniqueConstraint('nombre_estado_planificacion')
    )
    op.create_index(op.f('ix_estado_planificacion_cod_estado_planificacion'), 'estado_planificacion', ['cod_estado_planificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estado_planificacion_cod_estado_planificacion'), table_name='estado_planificacion')
    op.drop_table('estado_planificacion')
    # ### end Alembic commands ###
